### ISSUE TITLE
"document is not defined" build error

### ISSUE THREAD

**Issue by jlibbyibm** [carbon-design-system/ibm-cloud-cognitive#1887]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Upon updating to from carbon for ibm products 1.5.0 -> 1.12.0 a build error occurred saying 'document is not defined'. I was able to narrow down the version this started appearing in (for our code) somewhere between version 1.0.8 and 1.10.0.

Some environment details:
node 14.17.6
npm 6.14.15
nextjs 11.1.3 (also tried with nextjs 12)
react 16.14.0 (also tried with react 18)

> Is this issue related to a specific component?

The error message implies it is related to TagSet.js

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Build without errors.

> What browser are you working in?

The error occurred on npm build prior to being in a browser

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

1.12.0 (but as mentioned I believe it started earlier, approx 1.0.8-1.10.0)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Data Lake

## Steps to reproduce the issue

Reproduction steps are difficult as it is simply to build it with the above set up. There could be other environmental factors that I'm unaware of. We're not using the TagSet component which seems to be the trigger point so a guess is a dependency for the package that isn't always present.

## Additional information

Error message:
> Build error occurred
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/projectPath/node_modules/@carbon/ibm-products/lib/components/TagSet/TagSet.js:60:23)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/jeremylibby/Workspace/ui2/ui-management/node_modules/@carbon/ibm-products/lib/components/PageHeader/PageHeader.js:44:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) {
  type: 'ReferenceError'

**Comment by lee-chase** [comment]
@jlibbyibm the most recent release contains an update that may fix this. Are you able to confirm this is still an issue in 1.13.0?

**Comment by jlibbyibm** [comment]
It does appear to have fixed this issue as far as I can tell. Thank you! I'll close the issue
