### ISSUE TITLE
Fails to render SidePanel in SSR

### ISSUE THREAD

**Issue by s-onuma** [carbon-design-system/ibm-cloud-cognitive#2023]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

Server side rendering fails to render SidePanel with the following error message.
```
ReferenceError: window is not defined
    at /Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/@carbon/ibm-products/lib/components/SidePanel/SidePanel.js:134:23
    at /Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/@carbon/ibm-products/lib/settings.js:52:12
    at Jc (/Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:64:191)
    at Mc (/Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:69:169)
    at Z (/Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Nc (/Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
    at Pc (/Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
    at Z (/Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
    at Nc (/Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
    at Mc (/Users/s-onuma/workspace/carbon-sidepanel-ssg-example/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:131)
```

The above stack trace is of @carbon/ibm-products@1.19.1 but it happens with >= 1.6.0. (Probably https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1586)
We may need to check the existence of the `window` object by `typeof window !== "undefined"`

## Steps to reproduce the issue

I created a sample Github project with Next.js https://github.com/s-onuma/carbon-sidepanel-ssg-example
You can try `git clone`, `npm install` and `npm run build`. Then you'll see the error message above.

**Comment by matthewgallo** [comment]
This should be fixed in the latest release, let us know if you're still experiencing any issues!
