### ISSUE TITLE
TypeError: Object.hasOwn is not a function when running git commit

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#2384]
## What will this achieve?
Every time I commit to my branch I get the error below

```shell
✖ yarn stylelint:
TypeError: Object.hasOwn is not a function
    at _callee$ (/Users/melo/Desktop/ibm-cloud-cognitive/node_modules/stylelint-plugin-carbon-tokens/dist/rules/layout-token-use/utils/initAll.js:77:25)
    at tryCatch (/Users/melo/Desktop/ibm-cloud-cognitive/node_modules/stylelint-plugin-carbon-tokens/dist/rules/layout-token-use/utils/initAll.js:20:2404)
    at Generator._invoke (/Users/melo/Desktop/ibm-cloud-cognitive/node_modules/stylelint-plugin-carbon-tokens/dist/rules/layout-token-use/utils/initAll.js:20:1964)
    at Generator.next (/Users/melo/Desktop/ibm-cloud-cognitive/node_modules/stylelint-plugin-carbon-tokens/dist/rules/layout-token-use/utils/initAll.js:20:3255)
    at asyncGeneratorStep (/Users/melo/Desktop/ibm-cloud-cognitive/node_modules/stylelint-plugin-carbon-tokens/dist/rules/layout-token-use/utils/initAll.js:22:103)
    at _next (/Users/melo/Desktop/ibm-cloud-cognitive/node_modules/stylelint-plugin-carbon-tokens/dist/rules/layout-token-use/utils/initAll.js:24:194)
    at /Users/melo/Desktop/ibm-cloud-cognitive/node_modules/stylelint-plugin-carbon-tokens/dist/rules/layout-token-use/utils/initAll.js:24:364
    at new Promise (<anonymous>)
    at /Users/melo/Desktop/ibm-cloud-cognitive/node_modules/stylelint-plugin-carbon-tokens/dist/rules/layout-token-use/utils/initAll.js:24:97
    at doInit (/Users/melo/Desktop/ibm-cloud-cognitive/node_modules/stylelint-plugin-carbon-tokens/dist/rules/layout-token-use/utils/initAll.js:150:18)

```

## Steps I have done

1. Pull latest from main 
2. Deleted `yarn.lock` and `node_modules` and ran `yarn install`

## How will success be measured?
When i no longer have this error message.

## Additional information

- Designs
- Existing code
- etc

**Comment by AlexanderMelox** [comment]
Installing node 16 fixes the issue
