### ISSUE TITLE
latest code failed in webpack build because of lack of dependencies

### ISSUE THREAD

**Issue by yuecchen** [carbon-design-system/ibm-cloud-cognitive#355]
## What package(s) are you using?
```
    "@carbon/ibm-cloud-cognitive": "^0.1.63",
    "@carbon/ibm-cloud-cognitive-cdai": "1.1.1",
```
## Detailed description
here is parts of my devDependencies
```
    "@carbon/charts": "^0.29.1",
    "@carbon/ibm-cloud-cognitive": "^0.1.63",
    "@carbon/ibm-cloud-cognitive-cdai": "1.1.1",
    "@carbon/icons-react": "^10.9.2",
    "@carbon/layout": "^10.7.3",
    "@carbon/themes": "^10.9.3",
    "@carbon/type": "^10.8.3",
    "@carbon/grid": "^10.20.0",
```

while do webpack build, it turns out with error (firstly call for @crabon/grid, now @carbon/motion): 
```
ERROR in ./scss/common.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

@import '~@carbon/motion/scss/motion';
^
      File to import not found or unreadable: ~@carbon/motion/scss/motion.
      in /Users/yuecchen/projects/automation-saas/sre-console-ui/node_modules/@carbon/ibm-cloud-cognitive-cdai/scss/globals/scss/_carbon-settings.scss (line 15, column 1)
    at /Users/yuecchen/projects/automation-saas/sre-console-ui/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/yuecchen/projects/automation-saas/sre-console-ui/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/yuecchen/projects/automation-saas/sre-console-ui/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/yuecchen/projects/automation-saas/sre-console-ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/Users/yuecchen/projects/automation-saas/sre-console-ui/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/Users/yuecchen/projects/automation-saas/sre-console-ui/node_modules/neo-async/async.js:8069:18)
    at options.error (/Users/yuecchen/projects/automation-saas/sre-console-ui/node_modules/node-sass/lib/index.js:294:32)
 @ multi ./scss/common.scss common[0]
```

if `@carbon/ibm-cloud-cognitive-cdai` has dependencies, it should be added in to it's package.json

## Steps to reproduce the issue

1. Step one  
add following to devDependencies:
```
    "@carbon/charts": "^0.29.1",
    "@carbon/ibm-cloud-cognitive": "^0.1.63",
    "@carbon/ibm-cloud-cognitive-cdai": "1.1.1",
    "@carbon/icons-react": "^10.9.2",
    "@carbon/layout": "^10.7.3",
    "@carbon/themes": "^10.9.3",
    "@carbon/type": "^10.8.3",
    "@carbon/grid": "^10.20.0",
``` 
2. Step two  
install dependencies
```
npm install
```
3. Step three  
begin to do webpack build
```
npm run build
```

**Comment by SimonFinney** [comment]
@asfordmatt / @vladbalanescu Any thoughts on this one?

**Comment by andrea-gm** [comment]
@yuecchen @asfordmatt @vladbalanescu can we close this issue?

**Comment by andrea-gm** [comment]
@yuecchen @asfordmatt @vladbalanescu closing, please reopen if still relevant.
