### ISSUE TITLE
Compiled /lib/ files contain ES modules source in setIllustrationClass.js

### ISSUE THREAD

**Issue by nertzy** [carbon-design-system/ibm-cloud-cognitive#444]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

We upgraded to the latest version of `@carbon/ibm-cloud-cognitive-experimental` and ran our Jest specs. We got the following output:

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/dev/projects/syrup/node_modules/@carbon/ibm-cloud-cognitive-experimental/lib/components/EmptyStates/assets/setIllustrationClass.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import cx from 'classnames';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/@carbon/ibm-cloud-cognitive-experimental/lib/components/EmptyStates/EmptyState.js:14:52)
```

> Is this issue related to a specific component?

Yes, EmptyStates, probably.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected there to be CJS source in the `/lib/` directory subtree, instead of ES modules source.

> What browser are you working in?

> What version of the @carbon/ibm-cloud-cognitive packge are you using?

0.24.0

**Comment by matthewgallo** [comment]
This should be fixed now that #465 has been merged
